[package]
name = "gitlab-runner"
version = "0.0.2-alpha.1"
authors = ["Sjoerd Simons <sjoerd@collabora.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Helper crate to build custom gitlab runners"
homepage = "https://github.com/collabora/gitlab-runner-rs"
repository = "https://github.com/collabora/gitlab-runner-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.3", features = [ "json", "multipart" ] }
tokio = { version = "1.12.0", features = [ "full" ] }
url = "2.2.1"
serde = { version = "1.0.125", features = [ "derive" ] }
serde_json = "1.0.64"
env_logger = "0.9.0"
thiserror = "1.0.24"
bytes = "1.0.1"
zip = "0.5.12"
pin-project = "1.0.7"
futures = "0.3.15"
async-trait = "0.1.50"
log = "0.4.14"
tempfile = "3.2.0"

[dev-dependencies]
tokio = { version = "1.5.0", features = [ "full", "test-util" ] }
gitlab-runner-mock = { path = "../gitlab-runner-mock", version = "0.0.2-alpha.1" }
structopt = "0.3.21"
futures = "0.3.15"
